[project]
name = "morning-starter-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.5.5",
    "duckduckgo-search>=8.0.2",
    "generativeai>=0.0.1",
    "google-generativeai>=0.8.5",
]
